apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: node-app
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: node-app
  template:
    metadata:
      labels:
        run: node-app
    spec:
      containers:
      - image: gcr.io/pipeline-356718/node-app
        name: node-app
        ports:
        - containerPort: 3000